# Generated by Django 5.2.8 on 2025-12-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_area',
            fields=[
                ('area_id', models.AutoField(db_column='area_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('description', models.CharField(db_column='description', max_length=1000)),
            ],
            options={
                'db_table': 'activity_area',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(db_column='certificate_id', primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_column='certificate_number', max_length=50, unique=True)),
                ('certificate_type', models.CharField(db_column='certificate_type', max_length=50)),
                ('certificate_publisher', models.CharField(db_column='certificate_publisher', max_length=200)),
                ('status', models.CharField(choices=[('none', 'None'), ('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_column='status', default='valid', max_length=50)),
                ('qr_code_data', models.CharField(db_column='qr_code_data', max_length=500)),
                ('valid_from', models.DateField(db_column='valid_from')),
                ('valid_to', models.DateField(db_column='valid_to')),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='Certifying_unit',
            fields=[
                ('certifying_unit_id', models.AutoField(db_column='certifying_unit_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('address', models.CharField(db_column='address', max_length=500)),
                ('certifying_unit_code', models.CharField(db_column='certifying_unit_code', max_length=50, unique=True)),
                ('username', models.CharField(db_column='username', max_length=100, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'certifying_unit',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(db_column='company_id', primary_key=True, serialize=False)),
                ('company_type', models.CharField(db_column='company_type', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('email', models.CharField(db_column='email', max_length=100)),
                ('address', models.CharField(db_column='address', max_length=500)),
                ('country', models.CharField(db_column='country', default='Poland', max_length=100)),
                ('registration_number', models.CharField(db_column='registration_number', max_length=50)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
                ('website', models.CharField(db_column='website', max_length=255)),
                ('blockchain_address', models.CharField(db_column='blockchain_address', max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Certificate_status_history',
            fields=[
                ('history_id', models.AutoField(db_column='history_id', primary_key=True, serialize=False)),
                ('old_status', models.CharField(db_column='old_status', max_length=50)),
                ('new_status', models.CharField(db_column='new_status', max_length=50)),
                ('changed_by_user_id', models.IntegerField(db_column='changed_by_user_id')),
                ('changed_date', models.DateTimeField(auto_now_add=True, db_column='changed_date')),
                ('reason', models.CharField(db_column='reason', max_length=1000)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
            ],
            options={
                'db_table': 'certificate_status_history',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by_certifying_unit_id',
            field=models.ForeignKey(db_column='issued_by_certifying_unit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.CreateModel(
            name='Certifying_unit_certificates',
            fields=[
                ('jcc_id', models.AutoField(db_column='jcc_id', primary_key=True, serialize=False)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
                ('certifying_unit_id', models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certifying_unit')),
            ],
            options={
                'db_table': 'certifying_unit_certificates',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='holder_company_id',
            field=models.ForeignKey(db_column='holder_company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.company'),
        ),
        migrations.CreateModel(
            name='Company_activity_area',
            fields=[
                ('cod_id', models.AutoField(db_column='cod_id', primary_key=True, serialize=False)),
                ('area_id', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.activity_area')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.company')),
            ],
            options={
                'db_table': 'company_activity_area',
            },
        ),
        migrations.CreateModel(
            name='Consumer_rating',
            fields=[
                ('rating_id', models.AutoField(db_column='rating_id', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='rating', null=True)),
                ('comment', models.CharField(db_column='comment', max_length=1000)),
                ('consumer_email', models.CharField(db_column='consumer_email', max_length=100)),
                ('is_verified', models.IntegerField(db_column='is_verified', default=0)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
            ],
            options={
                'db_table': 'consumer_rating',
            },
        ),
        migrations.CreateModel(
            name='Notification_cert',
            fields=[
                ('notification_id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_column='notification_type', max_length=50)),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True)),
                ('sent_to', models.CharField(db_column='sent_to', max_length=100)),
                ('status', models.CharField(db_column='status', default='unsent', max_length=50)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
            ],
            options={
                'db_table': 'notification_cert',
            },
        ),
        migrations.CreateModel(
            name='Product_batch',
            fields=[
                ('batch_id', models.AutoField(db_column='batch_id', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=100)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('cn_code', models.CharField(db_column='cn_code', max_length=20)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Miligram'), ('p', 'Pieces')], db_column='unit_of_measure', max_length=20)),
                ('blockchain_hash', models.CharField(db_column='blockchain_hash', max_length=255)),
                ('status', models.CharField(db_column='status', default='waiting', max_length=50)),
                ('storage_conditions', models.CharField(db_column='storage_conditions', max_length=500)),
                ('transport_temperature', models.DecimalField(db_column='transport_temperature', decimal_places=2, max_digits=6)),
                ('harvest_date', models.DateField(blank=True, db_column='harvest_date', null=True)),
                ('production_date', models.DateField(db_column='production_date')),
                ('expiration_date', models.DateField(db_column='expiration_date')),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
                ('certifying_unit_id', models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certifying_unit')),
            ],
            options={
                'db_table': 'product_batch',
            },
        ),
        migrations.CreateModel(
            name='Fraud_report',
            fields=[
                ('report_id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('fraud_type', models.CharField(choices=[('fake_id', 'Fake ID'), ('fake_cert_id', 'Fake certification ID'), ('other', 'Other')], db_column='fraud_type', max_length=100)),
                ('reporter_email', models.CharField(db_column='reporter_email', max_length=100)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigation'), ('rejected', 'Rejected')], db_column='status', default='new', max_length=50)),
                ('investigation_notes', models.CharField(db_column='investigation_notes', max_length=1000)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.product_batch')),
            ],
            options={
                'db_table': 'fraud_reports',
            },
        ),
        migrations.CreateModel(
            name='Consumer_verification',
            fields=[
                ('verification_id', models.AutoField(db_column='verification_id', primary_key=True, serialize=False)),
                ('qr_code_scanned', models.CharField(db_column='qr_code_scanned', max_length=500)),
                ('verification_result', models.CharField(db_column='verification_result', max_length=50)),
                ('consumer_email', models.CharField(db_column='consumer_email', max_length=100)),
                ('consumer_ip', models.CharField(db_column='consumer_ip', max_length=45)),
                ('device_info', models.CharField(db_column='device_info', max_length=255)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.product_batch')),
            ],
            options={
                'db_table': 'consumer_verification',
            },
        ),
        migrations.CreateModel(
            name='Chain_event',
            fields=[
                ('event_id', models.AutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True, db_column='event_timestamp')),
                ('location', models.CharField(db_column='location', max_length=255)),
                ('blockchain_hash', models.CharField(db_column='blockchain_hash', max_length=255)),
                ('blockchain_tx_id', models.CharField(db_column='blockchain_tx_id', max_length=255)),
                ('area_id', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.activity_area')),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.company')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.product_batch')),
            ],
            options={
                'db_table': 'chain_event',
            },
        ),
        migrations.CreateModel(
            name='Batch_certificate',
            fields=[
                ('cp_id', models.AutoField(db_column='cp_id', primary_key=True, serialize=False)),
                ('certificate_id', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certificate')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.product_batch')),
            ],
            options={
                'db_table': 'batch_certificate',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(db_column='alert_id', primary_key=True, serialize=False)),
                ('alert_type', models.CharField(db_column='alert_type', max_length=100)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('severity', models.CharField(db_column='severity', max_length=50)),
                ('status', models.CharField(choices=[('done', 'Done'), ('new', 'New')], db_column='status', default='new', max_length=50)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.chain_event')),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.product_batch')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='Company_certifying_unit',
            fields=[
                ('ccu_id', models.AutoField(db_column='ccu_id', primary_key=True, serialize=False)),
                ('certifying_unit_id', models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.certifying_unit')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ProjektSystemCertyfikacji.company')),
            ],
            options={
                'db_table': 'company_certifying_unit',
                'unique_together': {('company_id', 'certifying_unit_id')},
            },
        ),
    ]
