# Generated by Django 5.2.8 on 2025-12-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certyfikat',
            fields=[
                ('certificate_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=20)),
                ('certificate_type', models.CharField(choices=[('inne', 'Inne'), ('produkcja', 'Produkcja')], default='inne', max_length=20)),
                ('holder_entity_id', models.IntegerField()),
                ('state', models.CharField(choices=[('none', 'None'), ('wazny', 'Wazny'), ('wygasly', 'Wygasly'), ('uniewazniony', 'Uniewazniony'), ('oczekujacy', 'Oczekujacy')], default='none', max_length=15)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('certificate_hash', models.CharField(max_length=100)),
                ('blockchain_address', models.CharField(max_length=100)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=15)),
                ('blockchain_address', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('area_of_activity', models.TextField(choices=[('prodction', 'Produkcja'), ('storage', 'Przechowywanie'), ('distribution', 'Dystrybucja'), ('import', 'Import'), ('export', 'Eksport')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jednostka_certyfikujaca',
            fields=[
                ('authority_id', models.AutoField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(max_length=30)),
                ('authority_address', models.TextField()),
                ('authority_ODU', models.CharField(max_length=30)),
                ('establishment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partia_produktow',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('inne', 'Inne'), ('warzywa', 'Warzywa'), ('owoce', 'Owoce'), ('nabial', 'Nabial'), ('mieso', 'Mieso')], default='inne', max_length=20)),
                ('codeCN', models.CharField(max_length=8)),
                ('production_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litr'), ('ml', 'Miligram'), ('szt', 'Sztuki')], default='szt', max_length=10)),
                ('blockchain_hash', models.CharField(max_length=64, unique=True)),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat')),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena_konsumenta',
            fields=[
                ('rating_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow')),
            ],
        ),
        migrations.CreateModel(
            name='Fraud_report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('fraud_type', models.CharField(choices=[('fake_id', 'Fake ID'), ('fake_cert_id', 'Fake certification ID'), ('inne', 'Inne')], max_length=100)),
                ('reporter_main', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('investigating', 'W toku'), ('rejected', 'Odrzucony')], default='new', max_length=50)),
                ('investigation_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat')),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('none', 'None'), ('error', 'Blad'), ('warning', 'Ostrzezenie')], default='none', max_length=10)),
                ('alert_severity', models.CharField(choices=[('niski', 'Niski'), ('krytyczny', 'Krytyczny')], default='niski', max_length=10)),
                ('alert_state', models.CharField(choices=[('none', 'None'), ('wykonane', 'Wykonane')], default='none', max_length=10)),
                ('event_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(max_length=255)),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow')),
            ],
        ),
        migrations.CreateModel(
            name='Weryfikacja_konsumenta',
            fields=[
                ('verification_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qr_code_scanned', models.CharField(max_length=255)),
                ('verification_result', models.BooleanField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow')),
            ],
        ),
        migrations.CreateModel(
            name='Jednostka_certyfikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat')),
                ('authority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.jednostka_certyfikujaca')),
            ],
            options={
                'unique_together': {('authority_id', 'certificate_id')},
            },
        ),
    ]
