# Generated by Django 5.2.8 on 2025-12-17 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
