# Generated by Django 4.2.21 on 2025-11-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='certicate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat'),
        ),
        migrations.AlterField(
            model_name='fraud_report',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow'),
        ),
        migrations.AlterField(
            model_name='fraud_report',
            name='certificate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat'),
        ),
        migrations.AlterField(
            model_name='jednostka_certyfikat',
            name='authority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.jednostka_certyfikujaca'),
        ),
        migrations.AlterField(
            model_name='jednostka_certyfikat',
            name='certificate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat'),
        ),
        migrations.AlterField(
            model_name='ocena_konsumenta',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow'),
        ),
        migrations.AlterField(
            model_name='partia_produktow',
            name='certificate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certyfikat'),
        ),
        migrations.AlterField(
            model_name='partia_produktow',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.entity'),
        ),
        migrations.AlterField(
            model_name='weryfikacja_konsumenta',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.partia_produktow'),
        ),
    ]
