# Generated by Django 5.2.8 on 2025-12-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='alert',
        ),
        migrations.AlterModelTable(
            name='certyfikat',
            table='certificate',
        ),
        migrations.AlterModelTable(
            name='entity',
            table='entity',
        ),
        migrations.AlterModelTable(
            name='fraud_report',
            table='fraud_report',
        ),
        migrations.AlterModelTable(
            name='jednostka_certyfikat',
            table='authority_certificate',
        ),
        migrations.AlterModelTable(
            name='jednostka_certyfikujaca',
            table='certifying_authority',
        ),
        migrations.AlterModelTable(
            name='ocena_konsumenta',
            table='consumer_rating',
        ),
        migrations.AlterModelTable(
            name='partia_produktow',
            table='product_batch',
        ),
        migrations.AlterModelTable(
            name='weryfikacja_konsumenta',
            table='consumer_verification',
        ),
    ]
