# Generated by Django 4.2.21 on 2025-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0002_alter_alert_batch_id_alter_alert_certicate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='certicate_id',
            new_name='certificate_id',
        ),
        migrations.AlterField(
            model_name='entity',
            name='area_of_activity',
            field=models.TextField(choices=[('production', 'Produkcja'), ('storage', 'Przechowywanie'), ('distribution', 'Dystrybucja'), ('import', 'Import'), ('export', 'Eksport')], max_length=30),
        ),
    ]
