# Generated by Django 5.2.8 on 2025-12-24 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0002_certificate_blockchain_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registration_code',
            },
        ),
        migrations.RemoveField(
            model_name='certifying_unit',
            name='email',
        ),
        migrations.RemoveField(
            model_name='certifying_unit',
            name='password',
        ),
        migrations.RemoveField(
            model_name='certifying_unit',
            name='username',
        ),
        migrations.AddField(
            model_name='certifying_unit',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifying_unit', to=settings.AUTH_USER_MODEL),
        ),

    ]
