# Generated by Django 5.2.8 on 2025-12-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0003_registrationcode_remove_certifying_unit_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifying_unit',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifying_unit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
