# Generated by Django 4.2.21 on 2025-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0003_rename_certicate_id_alert_certificate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='certificate_id',
            new_name='certicate_id',
        ),
        migrations.AlterField(
            model_name='entity',
            name='area_of_activity',
            field=models.TextField(choices=[('prodction', 'Produkcja'), ('storage', 'Przechowywanie'), ('distribution', 'Dystrybucja'), ('import', 'Import'), ('export', 'Eksport')], max_length=30),
        ),
    ]
