# Generated by Django 5.2.8 on 2025-12-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0004_certificate_blockchain_address_alter_alert_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifying_unit',
            name='is_approved',
            field=models.BooleanField(db_column='is_approved', default=False),
        ),
    ]
