# Generated by Django 4.2.21 on 2025-11-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0004_rename_certificate_id_alert_certicate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='certicate_id',
            new_name='certificate_id',
        ),
    ]
