# Generated by Django 5.2.8 on 2025-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0005_rename_certicate_id_alert_certificate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partia_produktow',
            name='qr_code_data',
        ),
        migrations.AddField(
            model_name='partia_produktow',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partia_produktow',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
