# Generated by Django 5.2.8 on 2026-01-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0005_certificate_blockchain_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('fraud_detected', 'Oszustwo wykryte'), ('expiry_warning', 'Ostrzeżenie o wygaśnięciu'), ('batch_issue', 'Problem z partią'), ('compliance_breach', 'Naruszenie zgodności ...')], db_column='alert_type', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.product_batch'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.chain_event'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Niskie'), ('medium', 'Średnie'), ('high', 'Wysokie'), ('critical', 'Krytyczne')], db_column='severity', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('done', 'Rozwiązane'), ('new', 'Nowe'), ('waiting', 'Oczekujące'), ('realising', 'W realizacji')], db_column='status', default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='batch_certificate',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.product_batch'),
        ),
        migrations.AlterField(
            model_name='batch_certificate',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
    ]
