# Generated by Django 5.2.8 on 2026-01-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0006_certificate_blockchain_address_and_more'),
    ]

    operations = [
    ]
