# Generated by Django 5.2.8 on 2025-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0006_remove_partia_produktow_qr_code_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certyfikat',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='partia_produktow',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='partia_produktow',
            name='qr_code_img',
        ),
        migrations.AddField(
            model_name='certyfikat',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certyfikat',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
