# Generated by Django 5.2.8 on 2026-01-16 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0007_auto_20260110_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_area',
            options={'verbose_name': 'Activity area', 'verbose_name_plural': 'Activity areas'},
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='batch_certificate',
            options={'verbose_name': 'Batch certificate', 'verbose_name_plural': 'Batches certificate'},
        ),
        migrations.AlterModelOptions(
            name='certificate_status_history',
            options={'verbose_name': 'Certificate status history', 'verbose_name_plural': 'Certificates status history'},
        ),
        migrations.AlterModelOptions(
            name='certifying_unit',
            options={'verbose_name': 'Certifying unit', 'verbose_name_plural': 'Certifying units'},
        ),
        migrations.AlterModelOptions(
            name='certifying_unit_certificates',
            options={'verbose_name': 'Certifying unit certificate', 'verbose_name_plural': 'Certifying unit certificates'},
        ),
        migrations.AlterModelOptions(
            name='chain_event',
            options={'verbose_name': 'Chain event', 'verbose_name_plural': 'Chain events'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='company_activity_area',
            options={'verbose_name': 'Company activity area', 'verbose_name_plural': 'Company activity areas'},
        ),
        migrations.AlterModelOptions(
            name='company_certifying_unit',
            options={'verbose_name': 'Company certifying unit', 'verbose_name_plural': 'Company certifying units'},
        ),
        migrations.AlterModelOptions(
            name='consumer_rating',
            options={'verbose_name': 'Consumer rating', 'verbose_name_plural': 'Consumer ratings'},
        ),
        migrations.AlterModelOptions(
            name='consumer_verification',
            options={'verbose_name': 'Consumer verification', 'verbose_name_plural': 'Consumers verification'},
        ),
        migrations.AlterModelOptions(
            name='fraud_report',
            options={'verbose_name': 'Fraud report', 'verbose_name_plural': 'Fraud reports'},
        ),
        migrations.AlterModelOptions(
            name='notification_cert',
            options={'verbose_name': 'Notification cert', 'verbose_name_plural': 'Notifications cert'},
        ),
        migrations.AlterModelOptions(
            name='product_batch',
            options={'verbose_name': 'Product batch', 'verbose_name_plural': 'Product batches'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_publisher',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='activity_areas',
            field=models.ManyToManyField(blank=True, help_text='Wybierz obszary działalności', related_name='certificates', to='ProjektSystemCertyfikacji.activity_area'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='allowed_activities',
            field=models.ManyToManyField(blank=True, db_table='certificate_allowed_activities', to='ProjektSystemCertyfikacji.activity_area'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='blockchain_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_type',
            field=models.CharField(choices=[('group_of_subjects', 'Grupa podmiotów'), ('subject', 'Podmiot')], db_column='subject_type', default='subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity_area',
            name='name',
            field=models.CharField(choices=[('production', 'Produkcja'), ('preparation', 'Przygotowanie'), ('introduction', 'Wprowadzenie'), ('storage', 'Przechowywanie'), ('import', 'Import'), ('export', 'Eksport')], db_column='name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='holder_company_id',
            field=models.ForeignKey(db_column='holder_company_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.company'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by_certifying_unit_id',
            field=models.ForeignKey(db_column='issued_by_certifying_unit_id', on_delete=django.db.models.deletion.PROTECT, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_column='status', default='valid', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate_status_history',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='certificate_status_history',
            name='changed_by_user_id',
            field=models.ForeignKey(db_column='changed_by_user_id', on_delete=django.db.models.deletion.PROTECT, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.AlterField(
            model_name='certificate_status_history',
            name='new_status',
            field=models.CharField(choices=[('valid', 'Ważny'), ('expired', 'Wygasł'), ('suspended', 'Zawieszony'), ('revoked', 'Anulowany')], db_column='new_status', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate_status_history',
            name='old_status',
            field=models.CharField(blank=True, choices=[('valid', 'Ważny'), ('expired', 'Wygasł'), ('suspended', 'Zawieszony'), ('revoked', 'Anulowany')], db_column='old_status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certifying_unit_certificates',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='certifying_unit_certificates',
            name='certifying_unit_id',
            field=models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.AlterField(
            model_name='chain_event',
            name='area_id',
            field=models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.activity_area'),
        ),
        migrations.AlterField(
            model_name='chain_event',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.product_batch'),
        ),
        migrations.AlterField(
            model_name='chain_event',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='chain_event',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('producer', 'Producent'), ('distributor', 'Dystrybutor'), ('certifier', 'Certyfikator'), ('warehouse', 'Magazyn'), ('import', 'Import'), ('export', 'Export')], db_column='company_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='company_activity_area',
            name='area_id',
            field=models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.activity_area'),
        ),
        migrations.AlterField(
            model_name='company_activity_area',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.company'),
        ),
        migrations.AlterField(
            model_name='company_certifying_unit',
            name='certifying_unit_id',
            field=models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.AlterField(
            model_name='company_certifying_unit',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.company'),
        ),
        migrations.AlterField(
            model_name='consumer_rating',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='consumer_rating',
            name='rating',
            field=models.IntegerField(db_column='rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='consumer_verification',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.product_batch'),
        ),
        migrations.AlterField(
            model_name='consumer_verification',
            name='verification_result',
            field=models.CharField(choices=[('authentic', 'Autentyczny'), ('suspicious', 'Podejrzany'), ('fake', 'Podrobiony')], db_column='verification_result', max_length=50),
        ),
        migrations.AlterField(
            model_name='fraud_report',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.product_batch'),
        ),
        migrations.AlterField(
            model_name='fraud_report',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='notification_cert',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='notification_cert',
            name='notification_type',
            field=models.CharField(choices=[('expiry_warning', 'Ostrzeżenie o wygaśnięciu'), ('status_change', 'Zmiana statusu'), ('suspension', 'Zawieszenie'), ('revocation', 'Anulowanie')], db_column='notification_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification_cert',
            name='status',
            field=models.CharField(choices=[('unsent', 'Niewysłane'), ('sent', 'Wysłane'), ('failed', 'Błąd'), ('bounced', 'Zwrócone')], db_column='status', default='unsent', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='certificate_id',
            field=models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.PROTECT, to='ProjektSystemCertyfikacji.certificate'),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='certifying_unit_id',
            field=models.ForeignKey(db_column='certifying_unit_id', on_delete=django.db.models.deletion.CASCADE, to='ProjektSystemCertyfikacji.certifying_unit'),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('in_circulation', 'W obiegu'), ('delivered', 'Dostarczone'), ('recalled', 'Wycofane')], db_column='status', default='waiting', max_length=50),
        ),
    ]
