# Generated by Django 5.2.8 on 2026-01-16 23:08

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0008_alter_activity_area_options_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE certificate DROP COLUMN IF EXISTS certificate_type;
                ALTER TABLE certificate DROP COLUMN IF EXISTS certificate_publisher;
            """,
            reverse_sql="""
                ALTER TABLE certificate ADD COLUMN certificate_type VARCHAR(50);
                ALTER TABLE certificate ADD COLUMN certificate_publisher VARCHAR(200);
            """
        ),
    ]