# Generated by Django 5.2.8 on 2026-01-16 23:12

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0009_drop_certificate_type_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE certificate 
                DROP COLUMN IF EXISTS certificate_publisher CASCADE;
                
                ALTER TABLE certificate 
                DROP COLUMN IF EXISTS certificate_type CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]