# Generated by Django 5.2.8 on 2026-01-16 23:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0010_auto_20260117_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_activity_areas',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('certificate', models.ForeignKey('Certificate', on_delete=models.CASCADE)),
                ('activity_area', models.ForeignKey('Activity_area', on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'certificate_activity_areas',
            },
        ),
    ]