# Generated by Django 5.2.8 on 2026-01-17 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0011_auto_20260117_0038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producent_id', models.AutoField(db_column='producer_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('address', models.CharField(db_column='address', max_length=500)),
                ('producer_code', models.CharField(db_column='producer_code', max_length=50, unique=True)),
                ('is_approved', models.BooleanField(db_column='is_approved', default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'db_table': 'producer',
            },
        ),
    ]
