# Generated by Django 5.2.8 on 2026-02-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0013_remove_certificate_allowed_activities_company_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(db_column='is_approved', default=False, null=True),
        ),
    ]
