# Generated by Django 5.2.8 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjektSystemCertyfikacji', '0015_remove_certificate_allowed_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files/'),
        ),
        migrations.AlterField(
            model_name='activity_area',
            name='name',
            field=models.CharField(choices=[('production', 'Produkcja'), ('preparation', 'Przygotowanie'), ('distribution', 'Distribution'), ('introduction', 'Dystrybucja/Wprowadzenie do obrotu'), ('storage', 'Przechowywanie'), ('import', 'Import'), ('export', 'Eksport')], db_column='name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('producer', 'Producent'), ('distributor', 'Dystrybutor'), ('warehouse', 'Magazyn'), ('import', 'Import'), ('export', 'Export')], db_column='company_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litr'), ('ml', 'Miligram'), ('p', 'Sztuk')], db_column='unit_of_measure', max_length=20),
        ),
    ]
